      - name: Build APK with Buildozer
        run: |
          # هذا الأمر سيبحث عن الملف ويظهره لنا لنعرف أين هو
          find . -name "buildozer.spec"
          # الأمر التالي سيقوم بالبناء من المجلد الرئيسي مباشرة
          buildozer android debug


